create table "public"."communities" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "spaceID" text not null
);

alter table "public"."communities" enable row level security;

CREATE UNIQUE INDEX communities_name_key ON public.communities USING btree (name);

CREATE UNIQUE INDEX communities_pkey ON public.communities USING btree (id);

alter table "public"."communities" add constraint "communities_pkey" PRIMARY KEY using index "communities_pkey";

alter table "public"."communities" add constraint "communities_name_key" UNIQUE using index "communities_name_key";
