name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: "npm i"
      - name: Typecheck
        run: "npx tsc"
      - name: Test
        run: "npm run test"
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: "npm i"
      - name: Publish Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
